<?php

namespace HZ\Wonja237Bundle\Repository;

/**
 * NewLetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewLetterRepository extends \Doctrine\ORM\EntityRepository
{
}
