<?php

namespace HZ\Wonja237Bundle\Repository;

/**
 * PublicitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicitesRepository extends \Doctrine\ORM\EntityRepository
{
}
